# Generated by Django 5.0 on 2024-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1Name', models.CharField(max_length=20)),
                ('player1Hp', models.IntegerField()),
                ('player2Name', models.CharField(max_length=20)),
                ('player2Hp', models.IntegerField()),
                ('winner', models.CharField(max_length=20)),
                ('timePlayed', models.CharField(max_length=20)),
                ('dateTime', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='match_history',
            field=models.ManyToManyField(blank=True, to='users.pongmatch'),
        ),
    ]
