# Generated by Django 5.0 on 2024-05-15 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pongmatch_customuser_match_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
