# Generated by Django 5.0 on 2024-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
