# Generated by Django 5.0 on 2024-05-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='match_history',
        ),
        migrations.DeleteModel(
            name='PongMatch',
        ),
    ]
