# Generated by Django 5.0 on 2024-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_match_history_delete_pongmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
