# Generated by Django 5.0 on 2024-06-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_email_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_otp_verified',
        ),
    ]
