# Generated by Django 5.0 on 2024-06-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_email_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
