# Generated by Django 5.0 on 2024-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_email_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('app', 'Auth-app'), ('email', 'Email'), ('none', 'None')], default='none', max_length=8, null=True),
        ),
    ]
