# Generated by Django 5.0 on 2024-06-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_email_otp_enabled_customuser_otp_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
