# Generated by Django 5.0 on 2024-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_email_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('app', 'Auth-app'), ('email', 'Email'), ('None', 'None')], default='none', max_length=8, null=True),
        ),
    ]
