# Generated by Django 5.0 on 2024-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_two_factor_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_otp_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
