
volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres-data
      o: bind
  django-data:
    driver: local
    driver_opts:
      type: none
      device: ./ft_transcendence
      o: bind
  

services:
  postgres:
    image: postgres
    env_file: ./ft_transcendence/.env
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    user: "${UID}:${GID}"
  # postgres_setup:
  #   image: postgres
  #   user: root
  #   volumes:
  #       - postgres-data:/var/lib/postgresql/data
  #   entrypoint: [ "bash", "-c", "chmod 755 -R /var/lib/postgresql/data && chmod 755 -R /etc/postgresql && chmod 755 -R /var/lib/postgresql/"] 
  #   depends_on:
  #       - postgres
  django:
    build: ./ft_transcendence/.
    volumes:
      - django-data:/ft_transcendence
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: ./ft_transcendence/.env