version: '3.8'

services:
  postgres:
    image: postgres
    env_file: ./ft_transcendence/.env
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  django:
    build: ./ft_transcendence/ 
    volumes:
      - ./ft_transcendence:/ft_transcendence
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: ./ft_transcendence/.env

volumes:
  postgres-data: