POST http://127.0.0.1:8000/users/create-user
Content-Type: application/json

{ "username": "kalle", "email": "testi@gmail.com", "password": "testisalis"}

###

POST http://127.0.0.1:8000/users/login-user
Content-Type: application/json

{ "username": "kalle", "password": "testisalis"}

###

GET http://127.0.0.1:8000/users/test-token
Content-Type: application/json
Authorization: Token bcfbe525af1dfc39277e1d49ba28ded45a3c59f9

{}
