POST http://127.0.0.1:8000/users/create-user
Content-Type: application/json

{ "username": "uusi", "email": "uusi@gmail.com", "password": "Testisalis123#", "confirm_password": "Testisalis123#"}

###

POST http://127.0.0.1:8000/users/create-user
Content-Type: application/json

{ "username": "mulli", "email": "mulli@gmail.com", "password": "Testisalis123#", "confirm_password": "Testisalis123#"}

###


POST http://127.0.0.1:8000/users/login-user
Content-Type: application/json

{ "username": "uusi", "password": "Testisalis123#"}

###

GET http://127.0.0.1:8000/users/test-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0Mzg3MTMzLCJpYXQiOjE3MTQzNzk5MzMsImp0aSI6Ijk5NDMyMDZhZjcxZDRhOTg4NGRmYjE3ZGQzMDVmMjJjIiwidXNlcl9pZCI6NDR9.ZR4yQ_shCFwWeK1GtBZNjZU-htVhhMyC5unAOhXG3gI

{}

###

GET http://127.0.0.1:8000/users/get-user/46/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0Mzk4NTkyLCJpYXQiOjE3MTQzOTEzOTIsImp0aSI6IjA3YmE4OGNhNGFkNTRlZGNhYTJmYzliZmI1NzRiOGFkIiwidXNlcl9pZCI6NDZ9.3Cm1uZbsGOMVCOmexWcmf1HD-cC5gtr1gaWHJrXXEc8

###

GET http://127.0.0.1:8000/users/get-user-profile/46/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0OTE4NDAyLCJpYXQiOjE3MTQ5MTEyMDIsImp0aSI6ImI0ZTUwZTZhYTQ4YjQzNzE4ZjMxOTRmMmM3MDQzOWQ3IiwidXNlcl9pZCI6NDZ9.RMw6gn0khu07JQOCseJVU7Hi_Fs7T1zsiPWfZpSah2c


###

PUT http://127.0.0.1:8000/users/update-user-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0OTE4NDAyLCJpYXQiOjE3MTQ5MTEyMDIsImp0aSI6ImI0ZTUwZTZhYTQ4YjQzNzE4ZjMxOTRmMmM3MDQzOWQ3IiwidXNlcl9pZCI6NDZ9.RMw6gn0khu07JQOCseJVU7Hi_Fs7T1zsiPWfZpSah2c

{ "username": "markoboy" }

###

POST http://127.0.0.1:8000/users/add-friend/46/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1MjY4NTgxLCJpYXQiOjE3MTUyNjEzODEsImp0aSI6IjdhMjA5OWViNGE2ZDRmNjFhZDAwN2U1MzBiZjQ5M2NmIiwidXNlcl9pZCI6NDd9.fRCgHBfBhE6dzujp2YWTzVDlK7bz1TB7xVRYK_bZVUY
