version: '3.8'

volumes:
  web-data:

networks:
  mynetwork:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-img:release
    container_name: nginx-cont
    ports:
      - "80:80"
    networks:
      - mynetwork
    restart: always
    volumes:
      - web-data:/var/www/html