version: '3.8'

volumes:
  web-data:
  postgres_data:
  pgadmin_data:

networks:
  mynetwork:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-img:release
    container_name: nginx-cont
    ports:
      - "80:80"
    networks:
      - mynetwork
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres-cont
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-cont
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    user: "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynetwork
    restart: always
    ports:
      - "5050:80"
