version: '3.8'

volumes:
  data:

networks:
  mynetwork:

#   nginx:
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile
#     image: nginx-img:release
#     container_name: nginx-cont
#     ports:
#       - "443:443"
#     networks:
#       - mynetwork
#     restart: always
#     volumes:
#       - data:/var/www/html
services:

  postgres:
    image: postgres:latest
    container_name: postgres-cont
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: pg
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    build:
      context: ./postgreSQL
      dockerfile: Dockerfile
    container_name: pgadmin-cont
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pw"
    volumes:
      - data:/var/lib/pgadmin
    networks:
      - mynetwork
    restart: always
    ports:
      - "8080:80"