version: '3.8'

volumes:
  postgres_data:
  pgadmin_data:
  certs:
  vault-id:

networks:
  mynetwork:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-cont
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - certs:/etc/nginx/ssl/
      - vault-id:/etc/vault/vault-id
    restart: always

  web:
    build: ./myproject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myproject:/code
    ports:
      - "8000:8000"
    depends_on:
      - vault
    networks:
      - mynetwork

  vault:
    build:
      context: ./vault
    container_name: vault-cont
    ports:
      - "8200:8200"
    volumes:
      - certs:/vault/certs/
      - vault-id:/etc/vault/vault-id
    networks:
      - mynetwork
    restart: always




  # postgres:
  #   image: postgres:latest
  #   container_name: postgres-cont
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: pg
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - mynetwork
  #   restart: always
  #   ports:
  #     - "5432:5432"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin-cont
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "root"
  #   user: "5050:5050"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   networks:
  #     - mynetwork
  #   restart: always
  #   ports:
  #     - "5050:80"
