# Generated by Django 5.0 on 2024-05-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_match_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dateTime',
            field=models.CharField(max_length=20),
        ),
    ]
