# Generated by Django 5.0 on 2024-06-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_match_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament_match',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(max_length=20)),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final', to='pong.match')),
                ('matchOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchOne', to='pong.match')),
                ('matchTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchTwo', to='pong.match')),
            ],
        ),
    ]
