# Generated by Django 5.0 on 2024-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_match_tournament_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
