# Generated by Django 5.0 on 2024-06-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_match_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='final',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='matchOne',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='matchTwo',
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_final',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_final', to='pong.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_one',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_one', to='pong.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_two',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_two', to='pong.match'),
        ),
    ]
