# Generated by Django 5.0 on 2024-06-03 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
