# Generated by Django 5.0 on 2024-06-03 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_tournament_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(default='Pong', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
